[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = "-C link-arg=-Ttests/rv64.lds"
runner = "qemu-system-riscv64 -smp 2 -m 256M -machine virt -nographic -chardev file,path=/dev/stdout,input-path=test_input.txt,mux=on,id=char1 -serial chardev:char1 -bios fw_jump64.elf -kernel "

[target.riscv32imac-unknown-none-elf]
rustflags = "-C link-arg=-Ttests/rv32.lds"
runner = "qemu-system-riscv32 -smp 2 -m 256M -machine virt -nographic -chardev file,path=/dev/stdout,input-path=test_input.txt,mux=on,id=char1 -serial chardev:char1 -bios fw_jump32.elf -kernel "
